apiVersion: project.harbor.crossplane.io/v1alpha1
kind: Project
metadata:
  name: test2
spec:
  forProvider:
    metadata:
      autoScan: "false"
      enableContentTrust: "false"
      enableContentTrustCosign: "false"
      preventVul: "false"
      public: "true"
      severity: "low"
      reuseSysCVEAllowlist: "true"
  providerConfigRef:
    name: example
